line-length = 88

[tool.ruff.lint]
select = ['ALL']
ignore = [
  'D100',
  'D104',
  'D101',
  'D102',
  'RET504',
  'D103',
  'PLR0913',
  'S101',
  'EM101',
  'TRY003',
  'D107',
  'ARG002',
  'RUF001',
  'TC003',
  'PLR0912',
  'C901',
  'N802',
  'PGH003',
  'TC002',
  'TC001',
]